### ISSUE TITLE
Add locations filter [BE] 

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/content-api#103]
We originally went for an `isOnline` boolean filter but will be changing it to be a regular dropdown offering `Online` and `In our building`

**Comment by rcantin-w** [comment]
We'll need to determine _how_ to pass it in the query. If it's a dropdown with a checkbox, it means the user can do these (query params are a suggestion);

- **Select only one option;**`location=online` or `location=inPerson`?
- **Select no option;** All are passed and it is not in the URL query, therefore it is not sent to the Content API in the query.
- **Select all options;** All are passed and it is in the URL query, therefore it IS sent to the Content API as part of the query. `location=online,inPerson`.

Honestly this might need more of a think, we'll have to hack the way it's done a bit to make it work, just need to discuss where the hacking happens and how.

**Comment by rcantin-w** [comment]
After our chat we think `locations=online,inOurBuilding`, with a logic based off of the one that's been there for almost two years:
https://github.com/wellcomecollection/wellcomecollection.org/issues/7818
https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/components/EventPromo/EventPromo.tsx#L35

**Comment by agnesgaroux** [comment]
in the event transformer, we'll need to format locations differently for filters and display
For display: leave as is
For filter: use same logic but reduce physical location (if present) to the less granular value of `in our building`
```
    filter: {
      formatId: format.id,
      isOnline: !!isOnline,
      interpretationIds: interpretations.map((i) => i.id),
      audienceIds: audiences.map((a) => a.id),
    },
    aggregatableValues: {
      format: JSON.stringify(format),
      interpretations: interpretations.map((i) => JSON.stringify(i)),
      audiences: audiences.map((a) => JSON.stringify(a)),
      location: JSON.stringify({
        type: "EventLocation",
        isOnline: !!isOnline,
      }),
    },
```
When an event is both online and in person, the location filter will be 
```
locations: [ "id for online", "id for in person"]
```
And either one or the other, still as an array of ids, if the event is not hybrid

**Comment by rcantin-w** [comment]
From a quick chat with Agnès, need a time to chat over [principle 1](https://github.com/wellcomecollection/docs/tree/main/rfcs/037-api-faceting-principles) and if we can make our idea for this filter match it better.

**Comment by jamieparkinson** [comment]
From discussion with Raphaëlle: proposal is to add a new property to event `location`s, provisionally called `attendance`
```
locations: [
  {
    "type": "EventLocation",
    "id": "Wn3ZFyoAACkAIgPT",
    "label": "The Studio",
    "attendance": [
      {
        "type": "EventAttendance",
        "id": "online",
        "label": "Online"
      },
      {
        "type": "EventAttendance",
        "id": "in-our-building",
        "label": "In our building"
      }
    ]
  }
]
```

then we can write filters like this:
```
GET /events?locations.attendance=online
```

**Comment by rcantin-w** [comment]
Looking at this again; would the label be whichever the first (physical) Location ends up being?

**Comment by rcantin-w** [comment]
Alright, @agnesgaroux and I white-boarded it, and we've come up with this;

```
  locations: {
    isOnline: boolean;
    places: {
      id: string;
      label: string;
      type: 'EventPlace';
    }[];
    attendance: {
      id: 'online' | 'in-our-building';
      label: 'Online' | 'In our building';
      type: 'EventAttendance';
    }[];
    type: 'EventLocations';
  };
};
```

filters will be using `locations.attendance`, and on the FE I can use `locations.isOnline` and `locations.places` to render out the correct location text following the rules listed above.
