### ISSUE TITLE
Add isAvailableOnline to content API

### ISSUE THREAD

**Issue by agnesgaroux** [wellcomecollection/content-api#109]
`isAvailableOnline` has been added to the event index
https://github.com/wellcomecollection/content-api/issues/107

The API needs to be updated to accept a new query param `isAvailableOnline`

Add an eventFilter like 
```
isAvailableOnline: (): QueryDslQueryContainer => ({
    term: {
      "filter.isAvailableOnline": true,
    },
  }),
```
ie. if the query param is present, its value is `true`

Add an event aggregation like 
```
isAvailableOnline: {
    terms: {
      size: 2,
      field: "aggregatableValues.isAvailableOnline",
    },
  },
```

**Comment by rcantin-w** [comment]
https://wellcomecollection.org/search/events?isAvailableOnline=true works nicely in prod
