### ISSUE TITLE
Research and answer questions for Events in "All" search

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/content-api#151]
- What to do with child/parent events?
- What to do with past dates?

**Comment by rcantin-w** [comment]
## Child/parents
The decision we made for `/events` was:

> Scheduled events must be findable/filterable based on their interpretation, audience, etc... which are not set on the parent
> The API returns the Parent event, not the Scheduled events to avoid duplication and/or events being listed without image or description.
   Basically we want to be able to match on a Scheduled event but return its parent in the API response.

Do we want to follow this here? Maybe some fields from the Scheduled events are pulled through and associated with the Parent event so they are still searchable, although I'm not sure which ones we'd want.

Scheduled events contain:
 - Location
 - Date
 - Reservation links/info
 - Interpretations/Audiences 

Its Parent event contains:
- Location
- Grouped dates (e.g. 12 December - 26 December)
- Reservation policies
- Interpretations/Audiences.

My feeling is that Scheduled event's info brings nothing to the table as for this search we said we'd display minimally:
- Type (Event) 
- Format 
- Title 
- UID 
- Description 
- Date (could/should be the Grouped Date)

And query minimally as well:
- Title 
- Format
- Type (Event)
- Standfirst/Promo caption 
- Contributors

All of these can come from the Parent only and we could stop Scheduled Events from indexing as we don't need them.

The only thing is if we want to start considering Interpretations/Audiences in the relevancy of results, it'll probably be important to consider the Scheduled Event's values, at which point we'd have to modify the Event transformer to allow for that. Do we think this will happen soon? I also don't really foresee this as a problem/something that would require us to break what we've built. It'll be building on top of. 


@davidpmccormick @LaurenFBaily

**Comment by rcantin-w** [comment]
## What to do with past dates?

This was in relation to the fact that in the mockup, event dates are displayed, even if in the past

![Image](https://github.com/user-attachments/assets/becbd693-e35b-4eae-b628-1668e01f1b2b)

Whereas currently, we don't do that in any listing page. Past events are shown as "Past" with a grey dot.

![Image](https://github.com/user-attachments/assets/9c26ac73-fee7-44f7-8a0c-89599297ed86)


We do see the value in displaying the date in the search, but a few questions come up then;

1. Should we change the logic everywhere to align?
2. Which date do we display in the event of a Parent/Scheduled event? (I'd recommend using the parent Grouped date (e.g. 12 December - 26 December)
3. Which date do we display in the event of a multi-date event (e.g. https://wellcomecollection.org/events/celebrating-who-i-am-november-december-2024). This is different from a Parent/Scheduled event in that it's only one Prismic document with a list of dates.

I think this one will be for @dana-saur and @LaurenFBaily to discuss, happy to join in!

**Comment by dana-saur** [comment]
I agree with everything @LaurenFBaily said above!

1. Rationale behind this is seeing the date of an event might be more helpful to help identify if it's the right result than if it's just 'past'. 
I personally think the metadata and tags on the cards/pages need to be revisited at some point anyways as the hierarchy doesn't quite make sense. I started looking into this when I was designing this but needed more thought than I had time for. I suspect this will come out of the concepts page designs at some point because of the tags. Maybe. 
3. If we can do the date range that would be ideal for consistency. If not, instead of a 'see all date/times' link could we have something like `Multiple dates/times, starting [first date]` I'm sure there's a more succinct way to say it though!

**Comment by rcantin-w** [comment]
OK thanks everyone for your inputs! I think the outcomes are:

## Child/parents
All we do with Scheduled events is filtering them OUT of the index. None of their information gets passed on to the Parent event.

## What to do with past dates?
1. No need to align with Event Cards
2. Using Parent event dates for display both for upcoming and past events.

Does that cover it?

**Comment by rcantin-w** [comment]
Closing the ticket which we can find again should we want the rationale for those decisions.
