### ISSUE TITLE
Audit addressable content types for descriptions

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/content-api#152]
- Promo captions
- Standfirst
- Intro text
- Metadata description
- "Featured" Text 

Audit out which content type uses what in reality, and which should be:
1. Displayed on the UI
2. Query-able. The thing to consider here would be that they shouldn't necessarily all be appended as it might skew the relevance.

**Comment by davidpmccormick** [comment]
I _think_ metadata description was primarily used to improve SEO. My instinct is that this would then be less appropriate as human-friendly search content?

**Comment by davidpmccormick** [comment]
Having looked through a sample of the content types and the fields mentioned above for each, I propose the following.

The metadata description is not consistently populated anywhere and I think it should be ignored for this piece of work altogether.

## Exhibition
- `promoText` appears to be the same as what was (pre-migration) a text block with the `featured` flag
- Doesn’t use `standfirst`
- **Recommend using `promo text` for query and display**

## Event
- Doesn’t use `featured` text or `standfirst`
- **Recommend using `promo text` for query and display**

## Story
- Standfirst is (usually?) different/longer from `promoText`
- **Recommend concatenating `promoText` and `stand first` for query, and `promoText` alone for display**

## Page
- We recently added `introText` (only appears on c. 3 at present). 
- **Recommend concatenating `promoText` and `introText` for query, and `promoText` alone for display**

## Visual Story
- `promoText` and `standfirst` can be very similar
- **Recommend using `promoText` alone for query and display**

## Exhibition text
- Doesn’t have `promoText` or `standfirst`
- **Use `intro_text` || the exhibition’s `promoText` if it isn’t filled, for query and display**

## Exhibition highlight tour
- Doesn’t have `promoText` or `standfirst`
- **Use `intro_text` || the exhibition’s `promoText` if it isn’t filled, for query and display**

## Book
- **Use `promoText` for query and display**

## Project
- **Use `promoText` for query and display**

## Season
- **Use `standfirst` concatenated with `promoText` for query, and `promoText` alone for display**

**Comment by rcantin-w** [comment]
Could you update the table with your findings 🙏 ? https://www.notion.so/wellcometrust/All-search-definition-acceptance-criteria-1366687658a180f28254d4429bf764ce

**Comment by rcantin-w** [comment]
How is this affected by [the standfirst changes ticket](https://github.com/wellcomecollection/wellcomecollection.org/issues/10753) and do we think it's something we should consider doing before doing this work?

**Comment by rcantin-w** [comment]
Sounds good. We'll need to make sure the Content API supports both until it gets fully removed, but I think after this piece of work, we'll _always_ have to think "How does my change affect the Content API" anyway.

**Comment by LaurenFBaily** [comment]
Reviewed and this all makes sense to me, minus the event question which is captured on a separate ticket anyway.
