### ISSUE TITLE
Define events index mapping

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/content-api#66]
**Phase 1**

To start with, mapping can be flexible but once we're ready for prod, we want to ensure our mapping is set.

The `display` section (see [articles mapping](https://github.com/wellcomecollection/content-api/blob/main/pipeline/src/indices/articles.ts#L11)) should be ignored/permissive.

**Comment by jamieparkinson** [comment]
I think the initial version of this, at least, is solved by https://github.com/wellcomecollection/content-api/issues/84
