### ISSUE TITLE
Events listing endpoint

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/content-api#67]
**Phase 1** 

Following on from https://github.com/wellcomecollection/content-api/issues/68 with an controller/test/etc `tests`, equivalent to `articles`. 

You should probably start off with just a paginated list, then we can work on adding a simple query.

**Comment by pollecuttn** [comment]
@georgiaewhitney I don't have permission to close this - can you do so, please.

**Comment by georgiaewhitney** [comment]
> @georgiaewhitney I don't have permission to close this - can you do so, please.

Ah apologies - only just spotted this!
