### ISSUE TITLE
Events; add missing fields to response

### ISSUE THREAD

**Issue by rcantin-w** [wellcomecollection/content-api#92]
To create the cards on the FE we need extra information that we're not currently providing;

- ~~`isRelaxedPerformance` to display as part of the primary labels. In Prismic, it's a boolean field at the root, but should we return as part of the access needs? I'm thinking this would probably be a good one to have in the filters wouldn't it? This one is on pause until we figure out what it's for ([See Slack thread](https://wellcome.slack.com/archives/C3N7J05TK/p1705594795269959))~~ won't do: [#10592](https://github.com/wellcomecollection/wellcomecollection.org/issues/10592)
- `audiences`; this we will need both for primary labels but also for the query as it'll become a filter. On the FE we just need an array of audiences' titles.
- `times.isFullyBooked` so we can update the event's status on the card as "Fully booked".
- `series`, probably just the series' title so we can display "Part of [series name]" on the card (or make it searchable as a query term?)

**Comment by agnesgaroux** [comment]
I noticed [ZWR9MRUAACUAVOIP](https://wellcomecollection.org/events/ZWR9MRUAACUAVOIP) is fully booked but this is not displayed on the card, only on the event page itself
Also, for scheduled events such as https://wellcomecollection.org/events/ZQgdkREAAAbr6cRR we can't tell the status, there's a "Check for tickets" button directing to Eventbrite
For consistency's sake I'm going to leave `isFullyBooked` and `onlineIsFullyBooked` from the display object

**Comment by rcantin-w** [comment]
Ohh interesting. I might have to investigate if that's on purpose or a bug as I think [there is code to display it](https://github.com/wellcomecollection/wellcomecollection.org/blob/main/content/webapp/components/EventPromo/EventPromo.tsx#L150).

I'll have a look this PM!

**Comment by rcantin-w** [comment]
As discussed, it _was_ a bug, so great find thank you! I have a PR here for it https://github.com/wellcomecollection/wellcomecollection.org/pull/10595 but I think I'll add a test to check it's there to prevent it happening again, so not 100% ready for review.

**Comment by rcantin-w** [comment]
As discussed just now, let's figure out more about isFullyBooked and how it works with `isFullyBooked`/`onlineIsFullyBooked` and the fact that there is one for every time. We'll need to figure out the logic as currently the cards on the FE only display "Fully booked" if BOTH `isFullyBooked`/`onlineIsFullyBooked`  are true, but we don't really see the sense in that (especially if an event isn't online).

I'll try to talk to editorial about it tomorrow morning, see what we can do as it'll be a bit of an intense day.
